auto instr = model.NewInstr("vzeroall");
UPDATE_R(YMM0, bv(0));
UPDATE_R(YMM1, bv(0));
UPDATE_R(YMM2, bv(0));
UPDATE_R(YMM3, bv(0));
UPDATE_R(YMM4, bv(0));
UPDATE_R(YMM5, bv(0));
UPDATE_R(YMM6, bv(0));
UPDATE_R(YMM7, bv(0));
UPDATE_R(YMM8, bv(0));
UPDATE_R(YMM9, bv(0));
UPDATE_R(YMM10, bv(0));
UPDATE_R(YMM11, bv(0));
UPDATE_R(YMM12, bv(0));
UPDATE_R(YMM13, bv(0));
UPDATE_R(YMM14, bv(0));
UPDATE_R(YMM15, bv(0));
instr.SetUpdate(rip, nxt_rip);
RECORD_INST("vzeroall");
